export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_ITEMS = 'SET_ITEMS';
export const SET_LOADING_INDICATOR = 'SET_LOADING_INDICATOR';
export const SET_LOADING_INDICATOR_FETCH_MORE = 'SET_LOADING_INDICATOR_FETCH_MORE';